#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-observe-kiali
#
# SYNOPSIS
#     lab-deploy {start|finish}
#
#        start - Deploy starter application into OpenShift Service Mesh
#        finish - Remove application project from OpenShift Service Mesh
#
# DESCRIPTION
#     This script is used to start/finish the chapter 3 section 6 guided exercise.
#
# CHANGELOG
#   * Wed May 04 2020 Ravi Srinivasan <ravis@redhat.com>
#   - Initial commit


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'

# Required by the do328 shlib
this='observe-kiali'
title='GE: Observing Service Interactions with Kiali'

istio_project='istio-system'
istio_deployment_name='basic-install'

declare -a valid_commands=(start finish)

function lab_start {

  ocp4_print_prereq_header
  ocp4_is_cluster_up
  ocp4_check_sm_installed ${istio_project} ${istio_deployment_name}

  ocp4_print_setup_header
  ocp4_grab_lab_files
  ocp4_login_as_developer
  ocp4_new_project "${this}"
  ocp4_sm_add_projects_to_smmr "${this}"
  ocp4_print_smmr_state_for_project "${this}"
  ocp4_wait_operator_ready "${this}"

  ocp4_pad 'Deploying application'
  if oc create -n "${this}" -f "${labs}/${this}/app-deployment.yaml"; then
    print_SUCCESS
  else
    print_FAIL
  fi

  ocp4_check_greet_app_pod_replicas "${this}"

  ocp4_print_setup_footer

}

function lab_finish {

  ocp4_print_cleanup_header

  ocp4_cleanup_lab_files
  ocp4_login_as_admin
  ocp4_sm_clean_smmr
  ocp4_delete_project "${this}"
  ocp4_logout

  ocp4_print_cleanup_footer

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
