apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
      annotations:
          sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: sleep
        image: quay.io/redhattraining/ossm-curl:1.0
        imagePullPolicy: Always
---
