apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: preference-vs
spec:
  hosts:
  - preference
  http:
  - route:
    - destination:
        host: preference
        port:
          number: 8080
    retries:
      attempts: 10
      perTryTimeout: 1s
      retryOn: 5xx
