apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
spec:
  name: jaeger-product
  source: ossm-catalog
  sourceNamespace: openshift-marketplace
  channel: "stable"
  installPlanApproval: Automatic
