apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  name: servicemeshoperator
  source: ossm-catalog
  sourceNamespace: openshift-marketplace
  channel: "1.0"
  installPlanApproval: Automatic
