apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    version: v1
  name: frontend-v1
spec:
  selector:
    matchLabels:
      app: frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: frontend-v1
          image: quay.io/redhattraining/ossm-adopt-a-pup-webapp:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_ADOPTION_SERVICE_URL
              value: "http://istio-ingressgateway-istio-system.apps.ocp4.example.com/"
            - name: REACT_APP_ANIMAL_SERVICE_URL
              value: "http://istio-ingressgateway-istio-system.apps.ocp4.example.com/"
            - name: REACT_APP_SHELTER_SERVICE_URL
              value: "http://istio-ingressgateway-istio-system.apps.ocp4.example.com/"
            - name: REACT_APP_NEWS_ENABLED
              value: "1"
            - name: BACKEND_NEWS_SERVICE_URL
              value: "http://news-adoptapup-news.apps.ocp4.example.com"
            - name: REACT_APP_EMAIL_APP_URL
              value: "http://email-adoptapup.apps.ocp4.example.com/"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
spec:
  hosts:
    - "*"
  gateways:
    - adoptapup-gateway
  http:
    - match:
        - uri:
            prefix: /frontend
      route:
        - destination:
            host: frontend
            port:
              number: 3000
